version: '3.8'
services:
  db:
    container_name: nico_mariadb_scholatech26
    image: mariadb:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
#      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: scholaTech26GORM
#      MYSQL_PASSWORD: 123456
      MYSQL_ALLOW_EMPTY_PASSWORD: 1

#  golang:
#    container_name: nico_golang_scholatech26
#    build:
#      context: .  # Usa el directorio actual como contexto
#      dockerfile: Dockerfile  # Especifica el Dockerfile que creaste
#    restart: always
#    ports:
#      - "8000:8000"  # Cambia este puerto según sea necesario
 #     - "5173:5173"
  redis:
    container_name: nico_redis_scholatech26
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"  # Puerto por defecto de Redis      
