version: '3.8'

services:
  db:
    container_name: nico_mariadb_scholatech26
    image: mariadb:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
#      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: scholaTech26GORM
#      MYSQL_PASSWORD: 123456
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    networks:
      scholanet:
          ipv4_address: 172.19.0.2
  golang:
    container_name: nico_golang_scholatech26
    build:
      context: .  
      dockerfile: dockerfile
    restart: always
    ports:
      - "8000:8000"  
      - "5173:5173"
    environment:
      WhereIam: "DOCKER"
    networks:
      scholanet:
        ipv4_address: 172.19.0.3
  redis:
    container_name: nico_redis_scholatech26
    image: redis:latest
    restart: always
    ports:
      - "6379:6379" 
    networks:
      scholanet:
          ipv4_address: 172.19.0.4
networks:
  scholanet:
    driver: bridge  
    ipam:
      config:
        - subnet: "172.19.0.0/16"